### ISSUE TITLE
Newline generated by inline R code removes the code after dedoc

### ISSUE THREAD

**Issue by shirdekel** [noamross/redoc#69]
## reprex.Rmd

YAML:

```
---
title: Reversible R Markdown Document
subtitle: Your subtitle
author: Your Name
date: Created `r Sys.Date()`
output:
  redoc::redoc:
    highlight_outputs: TRUE
    margins: 1 
    line_numbers: FALSE 
---
```

R code chunk:

```{r}
test1 <- "text1\ntext1"
test2 <- "text2\n\ntext2"
```

Inline:

```
`r test1`

`r test2`

`r "text3\n\ntext3"`

```

## Output

[reprex.docx](https://github.com/noamross/redoc/files/4390746/reprex.docx)

## Dedoc

YAML:

```
---
title: Reversible R Markdown Document
subtitle: Your subtitle
author: Your Name
date: Created `r Sys.Date()`
output:
  redoc::redoc:
    highlight_outputs: yes
    margins: 1
    line_numbers: no
---
```

R code chunk:

```{r}
test1 <- "text1\ntext1"
test2 <- "text2\n\ntext2"
```

Inline:

```
`r test1`

text2

text2

text3

text3
```

The inline R code is removed when it contains two `\n` instances, regardless of whether it was generated in a code chunk or inline.

---

<details> <summary><strong>Session Info</strong></summary>

```r
─ Session info ─────────────────────────
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_AU.UTF-8                 
 ctype    en_AU.UTF-8                 
 tz       Australia/Sydney            
 date     2020-03-27 
```

Pandoc version (get with rmarkdown::pandoc_version): 2.3.1

RStudio version (if applicable): 1.3.300

</details>
